### ISSUE TITLE
define own colors for lines in widget

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.eventlist#1]
I like this adapter  - would it be possibel that I define the colors of the line -  because if I use different colors for different states -the lines are very dark

eg:
odd lines white 
uneven lines lightgrey

**Comment by GermanBluefox** [comment]
Is it for Widget or for Admin?

**Comment by liv-in-sky** [comment]
for the widget

**Comment by GermanBluefox** [comment]
Actually I can offer only the work-around for that.
Apply to the widget some class: e.g. `ev-table` (not `event-table` as it is occupied)
![image](https://user-images.githubusercontent.com/4582016/96611625-27e0c580-12fd-11eb-9fa3-3ba0c58c0e85.png)

And then define in CSS the rules for this class:
![image](https://user-images.githubusercontent.com/4582016/96611787-52cb1980-12fd-11eb-85bb-d9a85dd79c4d.png)
```
.ev-table tr:nth-child(even) {
    background: #FF0000 !important;
}
.ev-table tr:nth-child(odd) {
    background: #00FF00 !important;
}
```

**Comment by liv-in-sky** [comment]
thanx a lot - is working

![Image 1](https://user-images.githubusercontent.com/18462890/96695574-15f93400-138a-11eb-8bb5-a74b50c027e0.png)
