### ISSUE TITLE
Quiting Fragen

### ISSUE THREAD

**Issue by danielalpha007** [ioBroker/ioBroker.eventlist#10]
Hallo, ich habe das nun ausprobiert, kriege es aber nicht zum laufen.

Einfügen:

sendTo('eventlist.0', 'insert', {
    event: 'Trockner hat keine Freigabe.. Über Visu einschalten!',
    id: '2'
});
Löschen:

// delete all events for specific state ID
sendTo('eventlist.0', 'delete', '2', result => {
    console.log(`Deleted ${result.count} events`);
});
Das schreiben vom Event geht, beim löschen schmiert der ganze Adapter ab. Auch die ID steht dran...

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.eventlist/issues/6
