### ISSUE TITLE
question: more than one instance?

### ISSUE THREAD

**Issue by Aare07** [ioBroker/ioBroker.eventlist#11]
Not a bug, an question:
I would like to use Eventlist in two different ways
Instance 0 with really important events I like to see in the VIS for all users of the house. Max 10 events in this list.
In instance 1 more technical events to see what's going on. I use this list as a kind of log and for statistical purposes with max 200 events in this list.
Filling mainly via script inserts and viewing via admin link

The idea is that i will install two instances and configure the list length accordingly.
This works so far

Now is it possible to call up the second instance via their own URL?  Something like <IP>: 8082/eventlist-1/
Is it possible to adapt the URL and file name of the generated PDF in instance 1? <IP>: 8082/eventlist/eventlist/report.pdf -> <IP>:8082/eventlist-1/eventlist-1/report-detail-1.pdf
Is ist possible to set the name (and path) of the report.pdf in the admin panel?

Thanks for your work and this great adapter
Greetings Aare

**Comment by GermanBluefox** [comment]
Use `http://IP:8082/eventlist/index.html?1` to see instance 1
and
`8082/eventlist/eventlist/report-1.pdf` (from 0.4.2)
