### ISSUE TITLE
Feature request: Hide rows in eventlist

### ISSUE THREAD

**Issue by Aare07** [ioBroker/ioBroker.eventlist#12]
A feature request:
It would be nice when the user could hide unwanted rows in the eventlist.
I do not need the row "State ID" and would like tho hide this row in the list and the PDF report
thank you
Greetings Aare

**Comment by GermanBluefox** [comment]
In PDF you can hide every column except Event itself.
In WEB view there is no stateID.
![image](https://user-images.githubusercontent.com/4582016/101262312-f3568b00-373d-11eb-8e23-b5f258c5aaa8.png)


I don't understand what is required.
