### ISSUE TITLE
Typo in der Admin-Sidebar

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.eventlist#13]
Hallo,
der Eventlist-Adapter wird ja in der Admin-Sidebar (ich hoffe die nennt man so) angezeigt, allerdings unter der Bezeichnung Ereignise.0 sollte das nicht Ereignisse.0 heissen?
Siehe Screenshot:
![image](https://user-images.githubusercontent.com/35137293/101284366-f5712600-37df-11eb-86db-be55e12aa170.png)
Gruß Steffen

**Comment by GermanBluefox** [comment]
Fixed in 0.5.0

**Comment by Steff42** [comment]
thx, looks good now!
