### ISSUE TITLE
Icons for manually inserted entries

### ISSUE THREAD

**Issue by maeb3** [ioBroker/ioBroker.eventlist#14]
Would be nice, if icons could be used for manually added entries also. 
Currently it seems that if I enter a new entry manually `sendTo('eventlist.0', 'insert', {event:'xxx'});`
that I can't add an icon, eg. `sendTo('eventlist.0', 'insert', {event:'myevent', ts:'my-time', icon:'/vis.0/main/images/my_icon.png'})`

**Comment by GermanBluefox** [comment]
Added in 0.5.0
