### ISSUE TITLE
js-controller 3.3.x

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.eventlist#16]
![grafik](https://user-images.githubusercontent.com/6681528/116673583-da2bd080-a9a3-11eb-8873-5bff430eea09.png)

**Comment by sigi2345** [comment]
Dito:

`

eventlist.0 | 2021-05-01 08:32:22.721 | warn | (16392) State value to set for "eventlist.0.lastEvent.id" has wrong type "boolean" but has to be "string"
-- | -- | -- | --
eventlist.0 | 2021-05-01 08:32:17.249 | warn | (16392) State value to set for "eventlist.0.lastEvent.id" has wrong type "boolean" but has to be "string"
eventlist.0 | 2021-05-01 08:28:54.491 | warn | (16392) State value to set for "eventlist.0.lastEvent.id" has wrong type "boolean" but has to be "string"
eventlist.0 | 2021-05-01 08:28:48.003 | warn | (16392) State value to set for "eventlist.0.lastEvent.id" has wrong type "boolean" but has to be "string"

`

**Comment by GermanBluefox** [comment]
Fixed in 0.5.0
