### ISSUE TITLE
Fehler im Auswahldialog

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.eventlist#2]
Spalte "Name, usw" wird im Auswahldialog nicht angezeigt.
JS-Controller: 3.1.6
Node.js: v12.18.3
NPM: 6.14.6

So schauts im Dialog aus:
![instances - ioBroker (2)](https://user-images.githubusercontent.com/45309436/94175038-61591900-fe96-11ea-8782-fc3b73649e6d.png)

So wie in den Objekten sollte es sein:
![objects - ioBroker (13)](https://user-images.githubusercontent.com/45309436/94175125-851c5f00-fe96-11ea-8a13-643a812c075b.png)

**Comment by Negalein** [comment]
> Adapter version?

0.2.6

**Comment by GermanBluefox** [comment]
Please test 0.2.8 tomorrow

**Comment by Negalein** [comment]
> Please test 0.2.8 tomorrow

Danke, funktioniert.
