### ISSUE TITLE
 Admin 5  type "string" but received type "boolean"

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.eventlist#22]
Admin 5 Info:

`
<html>
<body>

eventlist.0 | 2021-08-08 00:41:24.783 | info | State value to set for "eventlist.0.lastEvent.id" has to be type "string" but received type "boolean"
-- | -- | -- | --

</body>
</html>`

Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.4
NPM: 6.14.14
JS Controller: 3.3.15
Admin: 5.1.23
Web: 3.4.7
Socket.io: 3.1.4
Script Engine: 5.2.8

**Comment by GermanBluefox** [comment]
Fixed in 0.5.0

**Comment by sigi2345** [comment]
> Fixed in 0.5.0

Completed. THX
