### ISSUE TITLE
Doesn't work in IOBroker 5.1.25

### ISSUE THREAD

**Issue by jheisel01** [ioBroker/ioBroker.eventlist#25]
Hi,
The module doesn't work anymore in my IOBroker installation. 
I can't add objects to the eventlist. No option is shown.

![config_object_cr](https://user-images.githubusercontent.com/88741854/137639838-e7f895e7-b337-4959-9141-e8def978cb46.jpg)

Earlier entries work, but are also no longer displayed in the object configuration. A reinstallation of the adapter brought no change. Installed version is: 0.4.4

Debian Linux
IOBroker v5.1.25
Node.js  v12.22.7
NPM  6.14.15

regards,
Juergen

**Comment by Apollon77** [comment]
Configuration moved to main adaspter settings ... open this and install current version
