### ISSUE TITLE
Standarttext für nicht boolesche Zustände

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.eventlist#29]
Für boolesche Zustände kann ich ja angeben welcher Wert statt true und false angezeigt wird.

![Unbenannt](https://user-images.githubusercontent.com/77005685/155861908-9b14c92b-3bfe-4216-9170-f2e103c7356a.jpg)

Es wäre gut wenn ich das auch für nicht boolesche Zustände angeben könnte.
Z.B: "ON":"Ein","OFF":"Aus" ect.

**Comment by Bernd9000** [comment]
Scheint nicht zu funktionieren.
Aus true, false soll Ein,Aus werden.


![Unbenannt](https://user-images.githubusercontent.com/77005685/201535095-af227645-f774-4727-844f-c6a9159d52cb.jpg)

![Unbenannt2](https://user-images.githubusercontent.com/77005685/201535096-08a15feb-2ac1-4a55-8d59-e2f518d46953.jpg)

**Comment by GermanBluefox** [comment]
> Scheint nicht zu funktionieren. Aus true, false soll Ein,Aus werden. Im LOG kein Fehler.
> 

Kann es sein, dass die Werte "string" sind? Es werden nur neue Ereignisse umgewandelt.

**Comment by GermanBluefox** [comment]
Es hat nur für die Werte mit "states" funktioniert also, wo `common.states = {0: 'OFF, 1: 'ON'}`. jetzt habe ich das geändert.

**Comment by Bernd9000** [comment]
Danke
