### ISSUE TITLE
Fehler im PDF Einstellungsdialog

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.eventlist#3]
siehe auch ioBroker Forum: https://forum.iobroker.net/topic/37078/test-eventlist-adapter/29

Hallo,

mir ist folgender Fehler bei den Einstellungen im PDF-Dialog aufgefallen.

Zum nachvollziehen: Ich bin im Config-Dialog PDF --> siehe auch Screenshot
Dort gebe ich bei (1) eine neue Überschrift ein --> hier "Zeit"
Wie von Geisterhand wird bei (2) der selbe Text wie bei (1) eingetragen
Unter (2) kann ich gar nichts eingeben, der Klick wird ignoriert
Markiere ich unter (2) das Wort "Zeit" und gebe quasi Blind die gewünschte Überschrift ein z.B. "Wert" passiert in der Beispielansicht rechts (bei "3") ebenfalls nichts, es wird nur ein zusätzliches "t" angefügt.
![image](https://user-images.githubusercontent.com/35137293/94336778-ef8fe500-ffe5-11ea-8c4b-6712b643c7be.png)

Schaue ich mir nun die Eventliste oder die PDF-Eventliste an wurde die Überschrift aber korrekt übernommen --> siehe folgender Screenshot
![image](https://user-images.githubusercontent.com/35137293/94336786-00d8f180-ffe6-11ea-8aed-7fbceec45868.png)

Installiert ist Adapter Version 0.2.6

Gruß Steffen

**Comment by GermanBluefox** [comment]
Fixed in 0.2.8

**Comment by Steff42** [comment]
Works now like expected.
Issue can be closed.
Thx
