### ISSUE TITLE
Feature request: Change name of eventlist

### ISSUE THREAD

**Issue by BasBerends** [ioBroker/ioBroker.eventlist#35]
Hello,

I am using more then one eventlist (works great by the way!).

It would be nice when you can change the name of the eventlist. I attached a pic to explain what I mean.

Bas
![2022-03-10 (2)](https://user-images.githubusercontent.com/56431482/157688127-5edc9258-c378-4ebc-88e4-a556c12d99ff.png)

**Comment by GermanBluefox** [comment]
Implemented in 1.1.0
![image](https://user-images.githubusercontent.com/4582016/195307706-c7212fd1-e4fc-41c0-a37e-b932c9ac38b2.png)
