### ISSUE TITLE
Cannot set property 'color' of undefined

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.eventlist#44]
![grafik](https://user-images.githubusercontent.com/6681528/164659766-cd5a4edc-6e7f-4816-902e-12641ec5983b.png)

little problm here

**Comment by arteck** [comment]
and other one
![grafik](https://user-images.githubusercontent.com/6681528/164661926-54cf6d75-d03e-4506-8a36-3b70c6d0ddea.png)

**Comment by Apollon77** [comment]
What does the second one has to do with eventlist? This is an issue for homeconnect please!
