### ISSUE TITLE
Feature-Request: Subscribe to substates

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.eventlist#5]
Is it possible to subscribe to substates? For example to all states under hmrpc.0...?

**Comment by GermanBluefox** [comment]
**Step 1 -** Set the filter so, that only required states are visible:
![image](https://user-images.githubusercontent.com/4582016/96000784-91615f80-0e37-11eb-81b9-bd6623209177.png)

**Step 2** - Activate eventlist.
![image](https://user-images.githubusercontent.com/4582016/96000716-7f7fbc80-0e37-11eb-9c6f-d4d1a608a4a6.png)
