### ISSUE TITLE
Spalte Value bleibt leer

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.eventlist#52]
Auch wenn ein Wert (val:5) übergeben wird, so wird in der Liste in der Spalte "value" nichts angezeigt.

**Comment by Apollon77** [comment]
Kannst Du bitte etwas mehr Details liefern? Und ggf mal ein Debug Log posten? Danke

**Comment by Hirsch-DE** [comment]
Hallo,

der Fehler ist in 'main.js' bei Zeile 536
statt 
`if (valWithUnit !== '') {
        event.val = valWithUnit;
 }`
müsste es 
`if (valWithUnit !== '') {
        event.val = valWithUnit;
}else{
	event.val = val;
}`
lauten. Damit hat es bei mir funktioniert.
