### ISSUE TITLE
Beispiel in Readme funktioniert nicht

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.eventlist#53]
Das Beispiel: `setState('eventlist.0.insert', {event: 'My custom text', val: 5});` funktioniert nicht.
Es muss lauten `setState('eventlist.0.insert', JSON.stringify({event: 'My custom text %s', val: 5}));`

PS: Ich glaube, jemand hatte mal die Prüfung der Werte beim setzen von states im js-controller eingeführt! ;-)

**Comment by Apollon77** [comment]
Thank you for informing us!
