### ISSUE TITLE
Quiting

### ISSUE THREAD

**Issue by danielalpha007** [ioBroker/ioBroker.eventlist#6]
Hello, can you please implement a feature to automatically delete Notifications via javascript? 

Thanks

**Comment by danielalpha007** [comment]
Schade.. Der Ersteller schaut wohl leider nicht oft hier rein.. Sicher ist das bereits implementiert..

**Comment by GermanBluefox** [comment]
Ich verstehe nicht so ganz. Welche Notfications?

**Comment by danielalpha007** [comment]
> Ich verstehe nicht so ganz. Welche Notfications?

Schön das du doch hier rein schaust :=)

Ich würde gerne events aus der eventlist löschen lassen, wenn der alarmzustand auf 0 geht. 

Sprich: Wenn garagentor länger als 5 min offen ist, wird alarm ausgelöst: Garagentor länger als 5 min geöffnet!

Wird das Tor dann aber geschlossen, lasse ich den Alarm in IOBroker löschen, ich hätte gern, dass der Eintrag in der Eventlist dann gelöscht wird. Das muss ja dann ja auch über ein Script erreichen.

MfG

**Comment by GermanBluefox** [comment]
Alles klar. Ich werde 2 Szenarien implementieren, dass wenn Alarm auf 0 geht, dann Alle Alarm Zustande verschwunden ( einstellbar) oder man kann mit sendTo alle Alarme für Objekt X löschen oder nur Eintrag Y (bei Zeitstämpel)

**Comment by danielalpha007** [comment]
Dankeschön. Ansonsten super plug-ins die du machst 👌

Bluefox <notifications@github.com> schrieb am Di., 20. Okt. 2020, 08:54:

**Comment by GermanBluefox** [comment]
Implemented in v0.2.9

**Comment by danielalpha007** [comment]
Hallo, ich habe das nun ausprobiert, kriege es aber nicht zum laufen.

Einfügen: 

```
sendTo('eventlist.0', 'insert', {
    event: 'Trockner hat keine Freigabe.. Über Visu einschalten!',
    id: '2'
});
```

Löschen: 

```
// delete all events for specific state ID
sendTo('eventlist.0', 'delete', '2', result => {
    console.log(`Deleted ${result.count} events`);
});
```

**Comment by danielalpha007** [comment]
Push

**Comment by GermanBluefox** [comment]
Es nicht nicht klar, was willst du mit "2" löschen?

**Comment by GermanBluefox** [comment]
> Hallo, ich habe das nun ausprobiert, kriege es aber nicht zum laufen.
> 
> Einfügen:
> 
> ```
> sendTo('eventlist.0', 'insert', {
>     event: 'Trockner hat keine Freigabe.. Über Visu einschalten!',
>     id: '2'
> });
> ```
> 
> Löschen:
> 
> ```
> // delete all events for specific state ID
> sendTo('eventlist.0', 'delete', '2', result => {
>     console.log(`Deleted ${result.count} events`);
> });
> ```
> 
> Das schreiben vom Event geht, beim löschen schmiert der ganze Adapter ab. Auch die ID steht dran...

Es wird helfen wenn du die Logs hinzufügst.

**Comment by danielalpha007** [comment]
Hallo!
also..
wie ist es möglich, einen Eintrag hinzuzufügen, aber selbigen dann wieder zu entfernen, wenn ein Status eintritt...

Konkret: garagentor seit über 5 minuten geöffnet.. sobald es geschlossen ist, soll die Meldung verschwinden.

**Comment by danielalpha007** [comment]
huhu, schon eine Lösung dazu? 

LG

**Comment by danielalpha007** [comment]
Push

**Comment by danielalpha007** [comment]
Immernoch nicht gelöst.. Push

**Comment by Apollon77** [comment]
@danielalpha007 ... hm ... bzw Du hast immer noch keine Logs gezeigt wie am 5.12.2020  gebeten

**Comment by danielalpha007** [comment]
Hallo, ich kriege leider keine notifications aus dem Forum hier,

// delete all events
sendTo('eventlist.0', 'delete', '*', result => {
    console.log(`Deleted ${result.deleted} events`);
});

Sollte ja als javascript alle einträge löschen. 

Das log sagt: 

eventlist.0 | 2022-04-30 19:42:25.880 | info | undefined is not a valid state value for id "eventlist.0.lastEvent.id"


![image](https://user-images.githubusercontent.com/24484912/166116553-6742167c-4e14-4408-9dfc-0509b20f402d.png)

Zum schreiben:
// add custom event to event list
sendTo('eventlist.0', 'insert', {
    event: 'My custom text', 
    id: 'testtest',  // optional 
});

Liebe Grüße

**Comment by Apollon77** [comment]
Are you using the latestversion of the adapzter? There is no code where this could happen
