### ISSUE TITLE
Zustand lässt sich nicht deaktivieren

### ISSUE THREAD

**Issue by Marcel1285** [ioBroker/ioBroker.eventlist#7]
Bei einem Ereignis lassen sich die Zustände nicht deaktivieren.
Nach erfolgter Aktualisierung und erneutem aufrufen des Ereignisses ist der jeweilige Zustand wieder aktiviert.

**Comment by GermanBluefox** [comment]
Screenshot?

**Comment by MarcelW85** [comment]
![vor](https://user-images.githubusercontent.com/52207084/96405783-52882c80-11de-11eb-9393-29aa0e680ae8.PNG)

**Comment by GermanBluefox** [comment]
Ok. Danke. Werde schauen

**Comment by GermanBluefox** [comment]
Fixed in v0.2.9
